-- testdata in Artworks
insert into Artworks values(NULL, '抵柱铭', 'shufa', '40cmx30cm', './uploads/images/aw/sm/抵柱铭_small.jpg', './uploads/images/aw/mi/抵柱铭_middle.jpg', './uploads/images/aw/la/抵柱铭_large.jpg', 'author1', 'period1', '北宋黄庭坚 《抵柱铭》', 'this is the detail of 抵柱铭', 3000, 1, 2, 1, 0, 0);
insert into Artworks values(NULL, '局事贴', 'shufa', '50cmx60cm', './uploads/images/aw/sm/局事贴_small.jpg', './uploads/images/aw/mi/局事贴_middle.jpg', './uploads/images/aw/la/局事贴_large.jpg', 'author2', 'period2', '曾巩 《局事贴》', 'this is the detail of 局事贴', 3000, 1, 2, 1, 0, 0);
insert into Artworks values(NULL, '佛教艺术品', 'zhuanke', 'xxxxx', './uploads/images/aw/sm/佛教艺术品_small.jpg', './uploads/images/aw/mi/佛教艺术品_middle.jpg', './uploads/images/aw/la/佛教艺术品_large.jpg', 'author3', 'period3', '佛教艺术品', 'this is the detail of 佛教艺术品', 3000, 1, 2, 0, 0, 0);
insert into Artworks values(NULL, '黄杨木雕《小儿戏瓜》', 'zishahu', 'xxxxx', './uploads/images/aw/sm/黄杨木雕《小儿戏瓜》_small.jpg', './uploads/images/aw/mi/黄杨木雕《小儿戏瓜》_middle.jpg', './uploads/images/aw/la/黄杨木雕《小儿戏瓜》_large.jpg', 'author4', 'period4', 'this is the intro of 黄杨木雕《小儿戏瓜》', 'this is the detail of 黄杨木雕《小儿戏瓜》', 3000, 1, 2, 1, 0, 0);
insert into Artworks values(NULL, '蓝瓶', 'guohua', 'xxxxx', './uploads/images/aw/sm/蓝瓶_small.jpg', './uploads/images/aw/mi/蓝瓶_middle.jpg', './uploads/images/aw/la/蓝瓶_large.jpg', 'author5', 'period5', 'this is the intro of 蓝瓶', 'this is the detail of 蓝瓶', 3000, 1, 2, 1, 0, 0);
insert into Artworks values(NULL, '明代吴彬《十八应真图卷》', 'shufa', 'xxxxx', './uploads/images/aw/sm/明代吴彬《十八应真图卷》_small.jpg', './uploads/images/aw/mi/明代吴彬《十八应真图卷》_middle.jpg', './uploads/images/aw/la/明代吴彬《十八应真图卷》_large.jpg', 'author6', 'period5', 'this is the intro of 明代吴彬《十八应真图卷》', 'this is the detail of 明代吴彬《十八应真图卷》', 3000, 1, 2, 0, 0, 0);
insert into Artworks values(NULL, '平定西域献俘礼图', 'zhuake', 'xxxxx', './uploads/images/aw/sm/平定西域献俘礼图_small.jpg', './uploads/images/aw/mi/平定西域献俘礼图_middle.jpg', './uploads/images/aw/la/平定西域献俘礼图_large.jpg', 'author7', 'period6', 'this is the intro of 平定西域献俘礼图', 'this is the detail of 平定西域献俘礼图', 3000, 1, 2, 1, 0, 0);
insert into Artworks values(NULL, '清代钱维城国画手卷《雁荡图》', 'zhuake', 'xxxxx', './uploads/images/aw/sm/清代钱维城国画手卷《雁荡图》_small.jpg', './uploads/images/aw/mi/清代钱维城国画手卷《雁荡图》_middle.jpg', './uploads/images/aw/la/清代钱维城国画手卷《雁荡图》_large.jpg', 'author8', 'period7', 'this is the intro of 清代钱维城国画手卷《雁荡图》', 'this is the detail of 清代钱维城国画手卷《雁荡图》', 3000, 1, 2, 0, 0, 0);
insert into Artworks values(NULL, '张大千晚年巨幅泼彩绢画《爱痕湖》', 'shufa', '40cmx30cm', './uploads/images/aw/sm/张大千晚年巨幅泼彩绢画《爱痕湖》_small.jpg', './uploads/images/aw/mi/张大千晚年巨幅泼彩绢画《爱痕湖》_middle.jpg', './uploads/images/aw/la/张大千晚年巨幅泼彩绢画《爱痕湖》_large.jpg', 'author9', 'period8', '北宋黄庭坚 《张大千晚年巨幅泼彩绢画《爱痕湖》》', 'this is the detail of 张大千晚年巨幅泼彩绢画《爱痕湖》', 3000, 1, 2, 1, 0, 0);
insert into Artworks values(NULL, '元青花“鬼谷子下山”', 'shufa', '40cmx30cm', './uploads/images/aw/sm/元青花“鬼谷子下山”_small.jpg', './uploads/images/aw/mi/元青花“鬼谷子下山”_middle.jpg', './uploads/images/aw/la/元青花“鬼谷子下山”_large.jpg', 'author10', 'period9', '北宋黄庭坚 《元青花“鬼谷子下山”》', 'this is the detail of 元青花“鬼谷子下山”', 3000, 1, 2, 0, 0, 0);
insert into Artworks values(NULL, '元代王蒙国画《秋山萧寺图》', 'shufa', '40cmx30cm', './uploads/images/aw/sm/元代王蒙国画《秋山萧寺图》_small.jpg', './uploads/images/aw/mi/元代王蒙国画《秋山萧寺图》_middle.jpg', './uploads/images/aw/la/元代王蒙国画《秋山萧寺图》_large.jpg', 'author11', 'period10', '北宋黄庭坚 《元代王蒙国画《秋山萧寺图》》', 'this is the detail of 元代王蒙国画《秋山萧寺图》', 3000, 1, 2, 1, 0, 0);
insert into Artworks values(NULL, '陶瓷艺术品154', 'shufa', '40cmx30cm', './uploads/images/aw/sm/陶瓷艺术品154_small.jpg', './uploads/images/aw/mi/陶瓷艺术品154_middle.jpg', './uploads/images/aw/la/陶瓷艺术品154_large.jpg', 'author12', 'period11', '北宋黄庭坚 《陶瓷艺术品154》', 'this is the detail of 陶瓷艺术品154', 3000, 1, 2, 1, 0, 0);
insert into Artworks values(NULL, '请嘉庆御宝交龙钮翡翠玺', 'shufa', '40cmx30cm', './uploads/images/aw/sm/请嘉庆御宝交龙钮翡翠玺_small.jpg', './uploads/images/aw/mi/请嘉庆御宝交龙钮翡翠玺_middle.jpg', './uploads/images/aw/la/请嘉庆御宝交龙钮翡翠玺_large.jpg', 'author13', 'period12', '北宋黄庭坚 《请嘉庆御宝交龙钮翡翠玺》', 'this is the detail of 请嘉庆御宝交龙钮翡翠玺', 3000, 1, 2, 0, 0, 0);
insert into Artworks values(NULL, '清乾隆御宝“信天主人”交龙钮白玉玺', 'shufa', '40cmx30cm', './uploads/images/aw/sm/清乾隆御宝“信天主人”交龙钮白玉玺_small.jpg', './uploads/images/aw/mi/清乾隆御宝“信天主人”交龙钮白玉玺_middle.jpg', './uploads/images/aw/la/清乾隆御宝“信天主人”交龙钮白玉玺_large.jpg', 'author14', 'period12', '北宋黄庭坚 《清乾隆御宝“信天主人”交龙钮白玉玺》', 'this is the detail of 清乾隆御宝“信天主人”交龙钮白玉玺', 3000, 1, 2, 1, 0, 0);
insert into Artworks values(NULL, '清乾隆长颈葫芦瓶', 'shufa', '40cmx30cm', './uploads/images/aw/sm/清乾隆长颈葫芦瓶_small.jpg', './uploads/images/aw/mi/清乾隆长颈葫芦瓶_middle.jpg', './uploads/images/aw/la/清乾隆长颈葫芦瓶_large.jpg', 'author15', 'period13', '北宋黄庭坚 《清乾隆长颈葫芦瓶》', 'this is the detail of 清乾隆长颈葫芦瓶', 3000, 1, 2, 1, 0, 0);
