insert into Articles values(NULL, 'article name1', 'article1 article1 article1 article1 article1 article1 article1 article1 article1 article1 article1 article1 article1 article1 
article1 article1 article1 article1 article1 article1 article1 article1 article1 article1 article1 article1 
article1 article1 article1 article1
article1 article1 article1 article1 article1 article1 article1 article1 article1 article1 article1 article1 article1 article1 article1 article1 article1 article1 article1 article1 article1 article1 article1 article1 article1 article1 article1 article1 article1 article1 article1 article1 article1 article1 article1 article1 article1
article1 article1 article1 end of article1', '原创', '匿名', NULL, 0, 1, current_date(), 1, 0);
insert into Articles values(NULL, 'article name2', 'article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 article2 end of article2', '原创', '匿名', NULL, 0, 1, current_date(), 1, 0);
insert into Articles values(NULL, 'article name3', 'article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 article3 end of article3', '原创', '匿名', NULL, 0, 3, current_date(), 1, 0);
insert into Articles values(NULL, 'article name4', 'article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 article4 end of article4', '原创', '匿名', NULL, 0, 4, current_date(), 1, 0);
insert into Articles values(NULL, 'article name5', 'article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 article5 end of article5', '原创', '匿名', NULL, 1, 5, current_date(), 1, 0);
insert into Articles values(NULL, 'article name6', 'article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 article6 end of article6', '原创', '匿名', NULL, 1, 4, current_date(), 1, 0);
insert into Articles values(NULL, 'article name7', 'article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 article7 end of article7', '原创', '匿名', NULL, 1, 3, current_date(), 1, 0);
insert into Articles values(NULL, 'article name8', 'article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 article8 end of article8', '原创', '匿名', NULL, 1, 2, current_date(), 1, 0);

-- testdata in ArtworkTypes
insert into ArtworkTypes values(NULL, 'guohua', '国画', 1, NULL);
insert into ArtworkTypes values(NULL, 'shufa', '书法', 1, NULL);
insert into ArtworkTypes values(NULL, 'zhuanke', '篆刻', 1, NULL);
insert into ArtworkTypes values(NULL, 'zishahu', '紫砂壶', 1, NULL);
insert into ArtworkTypes values(NULL, 'qita', '其他', 1, NULL);
-- testdata in Artworks
insert into Artworks values(NULL, '抵柱铭', 'shufa', '40cmx30cm', './uploads/images/aw/sm/抵柱铭_small.jpg', './uploads/images/aw/mi/抵柱铭_middle.jpg', './uploads/images/aw/la/抵柱铭_large.jpg', 'author1', 'period1', '北宋黄庭坚 《抵柱铭》', 'this is the detail of 抵柱铭', 3000, 1, 2, 1, 0, 0);
insert into Artworks values(NULL, '局事贴', 'shufa', '50cmx60cm', './uploads/images/aw/sm/局事贴_small.jpg', './uploads/images/aw/mi/局事贴_middle.jpg', './uploads/images/aw/la/局事贴_large.jpg', 'author2', 'period2', '曾巩 《局事贴》', 'this is the detail of 局事贴', 3000, 1, 2, 1, 0, 0);
insert into Artworks values(NULL, '佛教艺术品', 'zhuanke', 'xxxxx', './uploads/images/aw/sm/佛教艺术品_small.jpg', './uploads/images/aw/mi/佛教艺术品_middle.jpg', './uploads/images/aw/la/佛教艺术品_large.jpg', 'author3', 'period3', '佛教艺术品', 'this is the detail of 佛教艺术品', 3000, 1, 2, 0, 0, 0);
insert into Artworks values(NULL, '黄杨木雕《小儿戏瓜》', 'zishahu', 'xxxxx', './uploads/images/aw/sm/黄杨木雕《小儿戏瓜》_small.jpg', './uploads/images/aw/mi/黄杨木雕《小儿戏瓜》_middle.jpg', './uploads/images/aw/la/黄杨木雕《小儿戏瓜》_large.jpg', 'author4', 'period4', 'this is the intro of 黄杨木雕《小儿戏瓜》', 'this is the detail of 黄杨木雕《小儿戏瓜》', 3000, 1, 2, 1, 0, 0);
insert into Artworks values(NULL, '蓝瓶', 'guohua', 'xxxxx', './uploads/images/aw/sm/蓝瓶_small.jpg', './uploads/images/aw/mi/蓝瓶_middle.jpg', './uploads/images/aw/la/蓝瓶_large.jpg', 'author5', 'period5', 'this is the intro of 蓝瓶', 'this is the detail of 蓝瓶', 3000, 1, 2, 1, 0, 0);
insert into Artworks values(NULL, '明代吴彬《十八应真图卷》', 'shufa', 'xxxxx', './uploads/images/aw/sm/明代吴彬《十八应真图卷》_small.jpg', './uploads/images/aw/mi/明代吴彬《十八应真图卷》_middle.jpg', './uploads/images/aw/la/明代吴彬《十八应真图卷》_large.jpg', 'author6', 'period5', 'this is the intro of 明代吴彬《十八应真图卷》', 'this is the detail of 明代吴彬《十八应真图卷》', 3000, 1, 2, 0, 0, 0);
insert into Artworks values(NULL, '平定西域献俘礼图', 'zhuake', 'xxxxx', './uploads/images/aw/sm/平定西域献俘礼图_small.jpg', './uploads/images/aw/mi/平定西域献俘礼图_middle.jpg', './uploads/images/aw/la/平定西域献俘礼图_large.jpg', 'author7', 'period6', 'this is the intro of 平定西域献俘礼图', 'this is the detail of 平定西域献俘礼图', 3000, 1, 2, 1, 0, 0);
insert into Artworks values(NULL, '清代钱维城国画手卷《雁荡图》', 'zhuake', 'xxxxx', './uploads/images/aw/sm/清代钱维城国画手卷《雁荡图》_small.jpg', './uploads/images/aw/mi/清代钱维城国画手卷《雁荡图》_middle.jpg', './uploads/images/aw/la/清代钱维城国画手卷《雁荡图》_large.jpg', 'author8', 'period7', 'this is the intro of 清代钱维城国画手卷《雁荡图》', 'this is the detail of 清代钱维城国画手卷《雁荡图》', 3000, 1, 2, 0, 0, 0);
insert into Artworks values(NULL, '张大千晚年巨幅泼彩绢画《爱痕湖》', 'shufa', '40cmx30cm', './uploads/images/aw/sm/张大千晚年巨幅泼彩绢画《爱痕湖》_small.jpg', './uploads/images/aw/mi/张大千晚年巨幅泼彩绢画《爱痕湖》_middle.jpg', './uploads/images/aw/la/张大千晚年巨幅泼彩绢画《爱痕湖》_large.jpg', 'author9', 'period8', '北宋黄庭坚 《张大千晚年巨幅泼彩绢画《爱痕湖》》', 'this is the detail of 张大千晚年巨幅泼彩绢画《爱痕湖》', 3000, 1, 2, 1, 0, 0);
insert into Artworks values(NULL, '元青花“鬼谷子下山”', 'shufa', '40cmx30cm', './uploads/images/aw/sm/元青花“鬼谷子下山”_small.jpg', './uploads/images/aw/mi/元青花“鬼谷子下山”_middle.jpg', './uploads/images/aw/la/元青花“鬼谷子下山”_large.jpg', 'author10', 'period9', '北宋黄庭坚 《元青花“鬼谷子下山”》', 'this is the detail of 元青花“鬼谷子下山”', 3000, 1, 2, 0, 0, 0);
insert into Artworks values(NULL, '元代王蒙国画《秋山萧寺图》', 'shufa', '40cmx30cm', './uploads/images/aw/sm/元代王蒙国画《秋山萧寺图》_small.jpg', './uploads/images/aw/mi/元代王蒙国画《秋山萧寺图》_middle.jpg', './uploads/images/aw/la/元代王蒙国画《秋山萧寺图》_large.jpg', 'author11', 'period10', '北宋黄庭坚 《元代王蒙国画《秋山萧寺图》》', 'this is the detail of 元代王蒙国画《秋山萧寺图》', 3000, 1, 2, 1, 0, 0);
insert into Artworks values(NULL, '陶瓷艺术品154', 'shufa', '40cmx30cm', './uploads/images/aw/sm/陶瓷艺术品154_small.jpg', './uploads/images/aw/mi/陶瓷艺术品154_middle.jpg', './uploads/images/aw/la/陶瓷艺术品154_large.jpg', 'author12', 'period11', '北宋黄庭坚 《陶瓷艺术品154》', 'this is the detail of 陶瓷艺术品154', 3000, 1, 2, 1, 0, 0);
insert into Artworks values(NULL, '请嘉庆御宝交龙钮翡翠玺', 'shufa', '40cmx30cm', './uploads/images/aw/sm/请嘉庆御宝交龙钮翡翠玺_small.jpg', './uploads/images/aw/mi/请嘉庆御宝交龙钮翡翠玺_middle.jpg', './uploads/images/aw/la/请嘉庆御宝交龙钮翡翠玺_large.jpg', 'author13', 'period12', '北宋黄庭坚 《请嘉庆御宝交龙钮翡翠玺》', 'this is the detail of 请嘉庆御宝交龙钮翡翠玺', 3000, 1, 2, 0, 0, 0);
insert into Artworks values(NULL, '清乾隆御宝“信天主人”交龙钮白玉玺', 'shufa', '40cmx30cm', './uploads/images/aw/sm/清乾隆御宝“信天主人”交龙钮白玉玺_small.jpg', './uploads/images/aw/mi/清乾隆御宝“信天主人”交龙钮白玉玺_middle.jpg', './uploads/images/aw/la/清乾隆御宝“信天主人”交龙钮白玉玺_large.jpg', 'author14', 'period12', '北宋黄庭坚 《清乾隆御宝“信天主人”交龙钮白玉玺》', 'this is the detail of 清乾隆御宝“信天主人”交龙钮白玉玺', 3000, 1, 2, 1, 0, 0);
insert into Artworks values(NULL, '清乾隆长颈葫芦瓶', 'shufa', '40cmx30cm', './uploads/images/aw/sm/清乾隆长颈葫芦瓶_small.jpg', './uploads/images/aw/mi/清乾隆长颈葫芦瓶_middle.jpg', './uploads/images/aw/la/清乾隆长颈葫芦瓶_large.jpg', 'author15', 'period13', '北宋黄庭坚 《清乾隆长颈葫芦瓶》', 'this is the detail of 清乾隆长颈葫芦瓶', 3000, 1, 2, 1, 0, 0);
insert into Links values(NULL, '谷歌', 'http://www.google.com', now());
insert into Links values(NULL, '维基百科', 'http://zh.wikipedia.org', now());
insert into Links values(NULL, '谷歌', 'http://www.google.com', now());
insert into Links values(NULL, '谷歌', 'http://www.google.com', now());
insert into Links values(NULL, '谷歌', 'http://www.google.com', now());
insert into Links values(NULL, '谷歌', 'http://www.google.com', now());
insert into Links values(NULL, '谷歌', 'http://www.google.com', now());
insert into Masters values(NULL, 'test0', sha1('astest'), 'test0@guyin.com', now(), 1);
insert into Masters values(NULL, 'test1', sha1('astest'), 'test1@guyin.com', now(), 0);
insert into Masters values(NULL, 'test2', sha1('astest'), 'test2@guyin.com', now(), 0);
insert into Masters values(NULL, 'test3', sha1('astest'), 'test3@guyin.com', now(), 0);
insert into Masters values(NULL, 'test4', sha1('astest'), 'test4@guyin.com', now(), 0);

-- testdata in Messages
insert into Messages values(NULL, 'message name1', 'message1 message1 message1 message1 message1 message1 message1 message1 message1 message1 message1 message1 message1 message1 message1 message1 message1 message1 message1 message1 message1 message1 message1 message1 message1 message1 message1 message1 message1 message1 message1 end of message1', now(), '匿名', '12345678', 9, NULL, 1, NULL);	-- 1
insert into Messages values(NULL, 'message name2', 'message2 message2 message2 message2 message2 message2 message2 message2 message2 message2 message2 message2 message2 message2 message2 end of message2', now(), '匿名', '6576523', 0, NULL, 1, NULL);	-- 2
insert into Messages values(NULL, 'message name3', 'message3 message3 message3 message3 message3 message3 message3 message3 message3 message3 message3 message3 message3 message3 message3 end of message3', now(), '匿名', '878687672', 0, NULL, 0, NULL);	-- 3
insert into Messages values(NULL, 'message name4', 'message4 message4 message4 message4 message4 message4 message4 message4 message4 message4 message4 message4 message4 message4 message4 end of message4', now(), '匿名', '767755768', 11, NULL, 0, NULL);	-- 4
insert into Messages values(NULL, 'message name5', 'message5 message5 message5 message5 message5 message5 message5 message5 message5 message5 message5 message5 message5 message5 message5 end of message5', now(), '匿名', '8787987', 0, NULL, 0, NULL);	-- 5
insert into Messages values(NULL, 'message name6', 'message6 message6 message6 message6 message6 message6 message6 message6 message6 message6 message6 message6 message6 message6 message6 end of message6', now(), '匿名', '7879878', 0, NULL, 0, NULL);	-- 6
insert into Messages values(NULL, 'message name7', 'message7 message7 message7 message7 message7 message7 message7 message7 message7 message7 message7 message7 message7 message7 message7 end of message7', now(), '匿名', '6768678', 0, NULL, 0, NULL);	-- 7
insert into Messages values(NULL, 'message name8', 'message8 message8 message8 message8 message8 message8 message8 message8 message8 message8 message8 message8 message8 message8 message8 end of message8', now(), '匿名', '234352', 10, NULL, 0, NULL);	-- 8
insert into Messages values(NULL, '回复1', '回复 回复 回复 回复 回复 回复 回复 回复 回复 回复 回复 回复 回复 回复 回复 end of 回复', now(), '匿名', '234352', 0, 1, 1, NULL);	-- 9
insert into Messages values(NULL, '回复2', '回复 回复 回复 回复 回复 回复 回复 回复 回复 回复 回复 回复 回复 回复 回复 end of 回复', now(), '匿名', '234352', 0, 8, 1, NULL);	-- 10
insert into Messages values(NULL, '回复3', '回复 回复 回复 回复 回复 回复 回复 回复 回复 回复 回复 回复 回复 回复 回复 end of 回复', now(), '匿名', '334353', 0, 4, 1, NULL);	-- 11
